version: '3.7'
services:
    stk-engine-custom-baseline:
        image: ansys/stk/stk-engine-custom-baseline:12.4.0-windowsservercore-ltsc2019
        build:
            context: .
            args:
                baseImage: ansys/stk/stk-engine-baseline:12.4.0-windowsservercore-ltsc2019
                pipIndexUrl: '' # Edit this value to be the index URL of your internal pip repository if you have one.
